- name: Update repositories cache and install "python3-pip" package
  ansible.builtin.apt:
    name: python3-pip
    update_cache: yes
    state: latest

- name: Install docker-compose python package
  ansible.builtin.pip:
    name: docker-compose
